name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: docker login
        env:
          DOCKER_USER: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login ${{ env.REGISTRY }} -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build the amd64 image
        run: docker build --build-arg opts="CGO_ENABLED=0 GOARCH=amd64" -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64 .
      - name: Build the arm64 image
        run: docker build --build-arg opts="GOARCH=arm64 GOARM=7" -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64v7 .

      - name: Docker Push amd64
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-amd64
      - name: Docker Push arm64v7
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-arm64v7